#9 Split work experience text by categories
kurnakovv/Resume pull request #17
Opened 2023-11-11 06:39 UTC by TanianaKur

2023-11-11 06:48 UTC, kurnakovv requested changes

2023-11-11 06:48 UTC, kurnakovv commented on index.html
>                    <p class="work-card__text">
We should use "p" node only for text, not for block. Html structure should by like that:
```html
<div class="work-card__main">
 <h2 class="work-card__h2">Title</h2>
 <p class="work-card__text">
  Text...
 </p>
 ...
</div>
```

2023-11-11 06:48 UTC, kurnakovv commented on css/style.css
> +.work-card__h2 {
`work-card__h2` is not best solution, because in html we can will change node. Let's name this `work-card__category`

2023-11-11 06:48 UTC, kurnakovv commented on css/style.css
> +  color: #7700ff;
White color better, please fix it

2023-11-13 13:16 UTC, kurnakovv requested changes
@TanianaKur new request changes

2023-11-13 13:16 UTC, kurnakovv commented on css/style.css
> +.work-card__category {
Category text must be thick

2023-11-13 13:16 UTC, kurnakovv commented on index.html
> +                  </p>
Add indentation between categories

2023-11-16 03:36 UTC, TanianaKur commented on css/style.css
> +.work-card__category {
what text thickness suits you?

2023-11-16 03:37 UTC, TanianaKur commented on index.html
> +                  </p>
what should the indent size be?

2023-11-16 08:21 UTC, kurnakovv commented on index.html
> +                  </p>
`font-weight: bold;`

2023-11-16 08:21 UTC, kurnakovv commented on css/style.css
> +.work-card__category {
`font-weight: bold;`

2023-12-10 11:08 UTC, kurnakovv requested changes
@TanianaKur issues has changes

2023-12-18 05:10 UTC, kurnakovv requested changes

2023-12-18 05:10 UTC, kurnakovv commented on index.html
> +                    - Develop second version of the product <br />- Write
No, we can't use br's, because it's bad practice. Think about better solution (I won't help you just yet, try to think for yourself)

2023-12-19 13:49 UTC, kurnakovv requested changes

2023-12-19 13:49 UTC, kurnakovv commented on index.html
> +                    >Senior developer</span
We will do this here #20 
Return "Junior developer"

2023-12-19 13:49 UTC, kurnakovv commented on index.html
> +                  <p class="work-card__text">
Don't use `<ul>` in `<p>`, because `<p>` must contain only text, not list.

2023-12-20 05:27 UTC, kurnakovv requested changes

2023-12-20 05:27 UTC, kurnakovv commented on index.html
> +                  <p class="work-card__text">
Sorry, I mean we must delete `<p>` and use only `<ul>` + `<li>` (return `<ul>` and delete `<p>`)

2023-12-20 05:47 UTC, kurnakovv commented
@TanianaKur you steal didn't do [this](https://github.com/kurnakovv/Resume/pull/17#discussion_r1431425438)

2023-12-20 05:48 UTC, kurnakovv requested changes

2023-12-20 05:48 UTC, kurnakovv commented on index.html
> +                  <ul class="work-card__text">
`work-card__text` is invalid, because this is not text. Create new style work-card__list or something similar

2023-12-20 12:33 UTC, kurnakovv requested changes

2023-12-20 12:33 UTC, kurnakovv commented on index.html
> +                  <ul class="work-card__list">
Well, you added `work-card__list` for html, but not for css. I think if `<ul>` don't need class attribute, let's delete it

2023-12-22 07:57 UTC, kurnakovv requested changes
@TanianaKur review

2023-12-22 07:57 UTC, kurnakovv commented on index.html
> +                    <li>- Develop second version of the product</li>
[Here](https://github.com/kurnakovv/Resume/issues/9#issuecomment-1864403177) I said delete `-`

2023-12-25 07:26 UTC, kurnakovv requested changes

2023-12-25 07:26 UTC, kurnakovv commented on css/style.css
> +.work-card_list {
1) Use double underscore `__`
2) This is not list, this is list item

Final name: `work-card__list-item`

2023-12-25 07:26 UTC, kurnakovv commented on index.html
> +                    <li class="work-card_list">
Let's use li and text in one line:
```
<li class="work-card_list">text</li>
```

2023-12-26 12:00 UTC, kurnakovv requested changes

2023-12-26 12:00 UTC, kurnakovv commented on index.html
> +                    <li class="work-card__list-">
Rename `work-card__list-` -> `work-card__list-item`

2023-12-26 12:00 UTC, kurnakovv commented on index.html
> +                    <li class="work-card__list-item">Develop architecture</li>
You didn't add correct format for `li`, let's do this for all `li` in file

2024-01-03 11:46 UTC, kurnakovv requested changes
@TanianaKur

2024-01-16 05:10 UTC, kurnakovv requested changes
@TanianaKur

2024-01-16 05:10 UTC, kurnakovv commented on .vscode/settings.json
> +    "liveServer.settings.port": 5501
What is it? Delete this file

2024-03-17 10:55 UTC, closed without merging